#!/usr/bin/env python3
"""
GitLab CI/CD Pipeline Generator

Detects project type and generates a starter .gitlab-ci.yml pipeline.
Supports: Node.js, Python, Go, Rust, Java/Maven, Docker, PHP, Ruby

Usage:
    python3 generate_pipeline.py [--type node|python|go|rust|java|docker|php|ruby|auto] [output-path]
"""

import sys
import os
import argparse
from pathlib import Path
from datetime import date

# ── Pipeline Templates ──────────────────────────────────────────────

TEMPLATES = {
    "node": {
        "detect_files": ["package.json"],
        "pipeline": '''# Generated by gitlab-ci-cd
# Node.js CI/CD Pipeline

stages:
  - build
  - test
  - deploy

variables:
  NODE_ENV: production

default:
  image: node:20-alpine
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# ── Build ──────────────────────────────────────────────────────────

install-dependencies:
  stage: build
  cache:
    key: \${CI_COMMIT_REF_SLUG}-npm
    paths:
      - .npm/
    policy: pull-push
  before_script:
    - mkdir -p .npm
    - export npm_config_cache=$CI_PROJECT_DIR/.npm
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
      - .npm/
    expire_in: 1 hour

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  needs:
    - install-dependencies
      artifacts: true

# ── Test ───────────────────────────────────────────────────────────

lint:
  stage: test
  script:
    - npm run lint
  needs:
    - install-dependencies
      artifacts: true
  allow_failure: true

unit-test:
  stage: test
  script:
    - npm test -- --ci --coverage
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml
    expire_in: 1 week
  coverage: '/All files[^|]*\\|[^|]*\\s*([\\d\\.]+)/'
  needs:
    - install-dependencies
      artifacts: true

# ── Deploy ─────────────────────────────────────────────────────────

deploy-staging:
  stage: deploy
  script:
    - echo "Deploying to staging..."
    - echo "Add your deployment commands here"
  environment:
    name: staging
    url: https://staging.example.com
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-production:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - echo "Add your deployment commands here"
  environment:
    name: production
    url: https://www.example.com
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/
      when: manual
''',
    },

    "python": {
        "detect_files": ["requirements.txt", "pyproject.toml", "setup.py", "Pipfile"],
        "pipeline": '''# Generated by gitlab-ci-cd
# Python CI/CD Pipeline

stages:
  - build
  - test
  - deploy

default:
  image: python:3.12-slim
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# ── Build ──────────────────────────────────────────────────────────

install-dependencies:
  stage: build
  cache:
    key: \${CI_COMMIT_REF_SLUG}-pip
    paths:
      - .cache/pip/
    policy: pull-push
  script:
    - pip install --cache-dir .cache/pip -r requirements.txt
  artifacts:
    paths:
      - .cache/pip/
    expire_in: 1 hour

# ── Test ───────────────────────────────────────────────────────────

lint:
  stage: test
  script:
    - pip install ruff || pip install flake8
    - ruff check . || flake8 .
  allow_failure: true
  needs:
    - install-dependencies
      artifacts: true

unit-test:
  stage: test
  script:
    - pip install pytest pytest-cov
    - pytest --junitxml=junit.xml --cov=. --cov-report=xml
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week
  coverage: '/TOTAL\\s+\\d+\\s+\\d+\\s+(\\d+%)/'
  needs:
    - install-dependencies
      artifacts: true

# ── Deploy ─────────────────────────────────────────────────────────

deploy-staging:
  stage: deploy
  script:
    - echo "Deploying to staging..."
    - echo "Add your deployment commands here"
  environment:
    name: staging
    url: https://staging.example.com
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-production:
  stage: deploy
  script:
    - echo "Deploying to production..."
  environment:
    name: production
    url: https://www.example.com
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/
      when: manual
''',
    },

    "go": {
        "detect_files": ["go.mod"],
        "pipeline": '''# Generated by gitlab-ci-cd
# Go CI/CD Pipeline

stages:
  - build
  - test
  - deploy

default:
  image: golang:1.22-alpine
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# ── Build ──────────────────────────────────────────────────────────

install-modules:
  stage: build
  cache:
    key: \${CI_COMMIT_REF_SLUG}-gomod
    paths:
      - .cache/go-mod/
    policy: pull-push
  script:
    - mkdir -p .cache/go-mod
    - export GOMODCACHE=$CI_PROJECT_DIR/.cache/go-mod
    - go mod download
  artifacts:
    paths:
      - .cache/go-mod/
    expire_in: 1 hour

build:
  stage: build
  script:
    - export GOMODCACHE=$CI_PROJECT_DIR/.cache/go-mod
    - go build -o bin/app ./...
  artifacts:
    paths:
      - bin/
    expire_in: 1 week
  needs:
    - install-modules
      artifacts: true

# ── Test ───────────────────────────────────────────────────────────

vet:
  stage: test
  script:
    - go vet ./...
  allow_failure: true
  needs:
    - install-modules
      artifacts: true

unit-test:
  stage: test
  script:
    - go test -v -coverprofile=coverage.out -json ./... | tee test-results.json
  artifacts:
    reports:
      coverage_report:
        coverage_format: gocover
        path: coverage.out
    expire_in: 1 week
  coverage: '/^.*\\s*(\\d+\\.\\d+)%/'
  needs:
    - install-modules
      artifacts: true

# ── Deploy ─────────────────────────────────────────────────────────

deploy-staging:
  stage: deploy
  script:
    - echo "Deploying to staging..."
  environment:
    name: staging
    url: https://staging.example.com
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-production:
  stage: deploy
  script:
    - echo "Deploying to production..."
  environment:
    name: production
    url: https://www.example.com
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/
      when: manual
''',
    },

    "rust": {
        "detect_files": ["Cargo.toml"],
        "pipeline": '''# Generated by gitlab-ci-cd
# Rust CI/CD Pipeline

stages:
  - build
  - test
  - deploy

default:
  image: rust:1.75-slim
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# ── Build ──────────────────────────────────────────────────────────

build:
  stage: build
  cache:
    key: \${CI_COMMIT_REF_SLUG}-cargo
    paths:
      - target/
    policy: pull-push
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/
    expire_in: 1 week

# ── Test ───────────────────────────────────────────────────────────

clippy:
  stage: test
  script:
    - cargo clippy -- -D warnings
  allow_failure: true
  needs: []

unit-test:
  stage: test
  script:
    - cargo test
  artifacts:
    reports:
      junit: target/test-results.xml
    expire_in: 1 week
  needs: []

# ── Deploy ─────────────────────────────────────────────────────────

deploy-staging:
  stage: deploy
  script:
    - echo "Deploying to staging..."
  environment:
    name: staging
    url: https://staging.example.com
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-production:
  stage: deploy
  script:
    - echo "Deploying to production..."
  environment:
    name: production
    url: https://www.example.com
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/
      when: manual
''',
    },

    "java": {
        "detect_files": ["pom.xml", "build.gradle", "build.gradle.kts"],
        "pipeline": '''# Generated by gitlab-ci-cd
# Java CI/CD Pipeline (Maven/Gradle)

stages:
  - build
  - test
  - deploy

default:
  image: maven:3.9-eclipse-temurin-21
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# ── Build ──────────────────────────────────────────────────────────

install-dependencies:
  stage: build
  cache:
    key: \${CI_COMMIT_REF_SLUG}-maven
    paths:
      - .m2/repository/
    policy: pull-push
  script:
    - mvn dependency:go-offline
  artifacts:
    paths:
      - .m2/repository/
    expire_in: 1 hour

build:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  needs:
    - install-dependencies
      artifacts: true

# ── Test ───────────────────────────────────────────────────────────

unit-test:
  stage: test
  script:
    - mvn test
  artifacts:
    reports:
      junit: target/surefire-reports/TEST-*.xml
    expire_in: 1 week
  coverage: '/Line.*?\\s+(\\d+\\.\\d+)%/'
  needs:
    - install-dependencies
      artifacts: true

# ── Deploy ─────────────────────────────────────────────────────────

deploy-staging:
  stage: deploy
  script:
    - echo "Deploying to staging..."
  environment:
    name: staging
    url: https://staging.example.com
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-production:
  stage: deploy
  script:
    - echo "Deploying to production..."
  environment:
    name: production
    url: https://www.example.com
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/
      when: manual
''',
    },

    "docker": {
        "detect_files": ["Dockerfile"],
        "pipeline": '''# Generated by gitlab-ci-cd
# Docker CI/CD Pipeline

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_NAME: $CI_REGISTRY_IMAGE

default:
  services:
    - name: docker:dind
      alias: docker
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# ── Build ──────────────────────────────────────────────────────────

docker-login:
  stage: build
  image: alpine
  before_script:
    - apk add --no-cache docker
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

docker-build:
  stage: build
  image: docker:24-dind
  cache:
    key: \${CI_COMMIT_REF_SLUG}-docker
    paths:
      - .docker-cache/
    policy: pull-push
  script:
    - docker build
      --cache-from $IMAGE_NAME:buildcache
      --cache-from $IMAGE_NAME:latest
      -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
      -t $IMAGE_NAME:latest
      --build-arg BUILDKIT_INLINE_CACHE=1
      .
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

docker-push:
  stage: build
  image: docker:24-dind
  script:
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

# ── Test ───────────────────────────────────────────────────────────

docker-lint:
  stage: test
  image: docker:24-dind
  before_script:
    - apk add --no-cache curl
    - curl -sSfL https://github.com/projectatomic/dockerfile_lint/releases/download/v1.0.1/dockerfile_lint -o dockerfile_lint
    - chmod +x dockerfile_lint
  script:
    - ./dockerfile_lint Dockerfile
  allow_failure: true
  needs: []

# ── Deploy ─────────────────────────────────────────────────────────

deploy-staging:
  stage: deploy
  script:
    - echo "Deploying $IMAGE_NAME:$CI_COMMIT_SHORT_SHA to staging..."
  environment:
    name: staging
    url: https://staging.example.com
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-production:
  stage: deploy
  script:
    - echo "Deploying $IMAGE_NAME:$CI_COMMIT_TAG to production..."
  environment:
    name: production
    url: https://www.example.com
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/
      when: manual
''',
    },

    "php": {
        "detect_files": ["composer.json"],
        "pipeline": '''# Generated by gitlab-ci-cd
# PHP CI/CD Pipeline

stages:
  - build
  - test
  - deploy

default:
  image: php:8.3-cli
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# ── Build ──────────────────────────────────────────────────────────

install-dependencies:
  stage: build
  cache:
    key: \${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
      - .composer/cache/
    policy: pull-push
  before_script:
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install --no-interaction --prefer-dist
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hour

# ── Test ───────────────────────────────────────────────────────────

phpstan:
  stage: test
  script:
    - composer require --dev phpstan/phpstan
    - vendor/bin/phpstan analyse --level=5 src/
  allow_failure: true
  needs:
    - install-dependencies
      artifacts: true

unit-test:
  stage: test
  script:
    - composer require --dev phpunit/phpunit
    - vendor/bin/phpunit --coverage-clover=coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: clover
        path: coverage.xml
    expire_in: 1 week
  needs:
    - install-dependencies
      artifacts: true

# ── Deploy ─────────────────────────────────────────────────────────

deploy-staging:
  stage: deploy
  script:
    - echo "Deploying to staging..."
  environment:
    name: staging
    url: https://staging.example.com
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-production:
  stage: deploy
  script:
    - echo "Deploying to production..."
  environment:
    name: production
    url: https://www.example.com
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/
      when: manual
''',
    },

    "ruby": {
        "detect_files": ["Gemfile"],
        "pipeline": '''# Generated by gitlab-ci-cd
# Ruby CI/CD Pipeline

stages:
  - build
  - test
  - deploy

default:
  image: ruby:3.3-slim
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

# ── Build ──────────────────────────────────────────────────────────

install-dependencies:
  stage: build
  cache:
    key: \${CI_COMMIT_REF_SLUG}-gems
    paths:
      - vendor/bundle/
    policy: pull-push
  before_script:
    - gem install bundler
    - bundle config set path 'vendor/bundle'
  script:
    - bundle install --jobs $(nproc || echo 4)
  artifacts:
    paths:
      - vendor/bundle/
    expire_in: 1 hour

# ── Test ───────────────────────────────────────────────────────────

rubocop:
  stage: test
  script:
    - bundle exec rubocop
  allow_failure: true
  needs:
    - install-dependencies
      artifacts: true

unit-test:
  stage: test
  script:
    - bundle exec rspec --format progress --format RspecJunitFormatter --out junit.xml
  artifacts:
    reports:
      junit: junit.xml
    expire_in: 1 week
  needs:
    - install-dependencies
      artifacts: true

# ── Deploy ─────────────────────────────────────────────────────────

deploy-staging:
  stage: deploy
  script:
    - echo "Deploying to staging..."
  environment:
    name: staging
    url: https://staging.example.com
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-production:
  stage: deploy
  script:
    - echo "Deploying to production..."
  environment:
    name: production
    url: https://www.example.com
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\\d+\\.\\d+\\.\\d+$/
      when: manual
''',
    },
}

# ── Auto-detection ─────────────────────────────────────────────────

def detect_project_type(project_dir="."):
    """Detect project type from files in the directory."""
    for project_type, config in TEMPLATES.items():
        for detect_file in config["detect_files"]:
            if os.path.isfile(os.path.join(project_dir, detect_file)):
                return project_type
    return None


def generate(project_type="auto", project_dir=".", output_path=None):
    """Generate a pipeline file."""
    if project_type == "auto":
        detected = detect_project_type(project_dir)
        if detected is None:
            print("Could not auto-detect project type.")
            print("Supported types: " + ", ".join(TEMPLATES.keys()))
            print("Use --type to specify manually.")
            sys.exit(1)
        project_type = detected
        print(f"Detected project type: {project_type}")

    if project_type not in TEMPLATES:
        print(f"Unknown project type: {project_type}")
        print(f"Supported: {', '.join(TEMPLATES.keys())}")
        sys.exit(1)

    pipeline = TEMPLATES[project_type]["pipeline"]

    if output_path is None:
        output_path = ".gitlab-ci.yml"

    output = os.path.join(project_dir, output_path)
    with open(output, "w", encoding="utf-8") as f:
        f.write(pipeline)

    print(f"Generated: {output}")
    return output


def main():
    parser = argparse.ArgumentParser(description="Generate a GitLab CI/CD pipeline")
    parser.add_argument(
        "--type",
        choices=list(TEMPLATES.keys()) + ["auto"],
        default="auto",
        help="Project type (default: auto-detect)",
    )
    parser.add_argument(
        "output",
        nargs="?",
        default=None,
        help="Output file path (default: .gitlab-ci.yml)",
    )
    args = parser.parse_args()

    generate(args.type, ".", args.output)


if __name__ == "__main__":
    main()
